function [ deflection, energyOneSpring ] = ...
    jumperDeflection(uncompressedLength, ...
                     compressedLength, ...
                     springWidth, ...
                     springThickness, ...
                     numberOfSprings, ...
                     numberOfElements, ...
                     youngsModulus)

dLength = uncompressedLength / numberOfElements;  % m

secondMomentOfArea = springWidth * springThickness^3 / 12;  % m^4

torsionalStiffness = youngsModulus * secondMomentOfArea / dLength; % N-m 

initialDeflection = pi / (numberOfElements + 1) * ones(1, numberOfElements);

[deflection, energyOneSpring] = ...
    fmincon(@(deflection) energyFun(deflection, torsionalStiffness), ...
            initialDeflection, ...
            [], [], [], [], [], [], ...
            @(deflection) constraintFun(deflection, ...
                                        dLength, ...
                                        compressedLength));


end
