function specificDrag = jumperSpecificDrag(mass_payload, ...
                                           drag_area, ...
                                           springEnergy, ...
                                           springMass, ...
                                           dragMassPerArea, ...
                                           dragCoefficient, ...
                                           massHinge, ...
                                           airDensity, ...
                                           gravity)

specificDrag = ...
    2*(dragCoefficient * airDensity * drag_area * ...
       (mass_payload + drag_area * dragMassPerArea + ...
        .5*(springMass + massHinge)) * springEnergy) / ...
    ((mass_payload + drag_area * dragMassPerArea + ...
      springMass + massHinge)^3 * gravity);

end
