function velocity = velocityFunction(mass_payload, ...
                                     drag_area, ...
                                     totalEnergy, ...
                                     springMass, ...
                                     dragMassPerArea, ...
                                     numberOfSprings, ...
                                     massHinge, ...
                                     dragCoefficient, ...
                                     gravity, ...
                                     airDensity)

    efficiency = jumperEfficiency(massHinge, ...
                                  numberOfSprings, ...
                                  springMass / numberOfSprings, ...
                                  mass_payload);
    
    totalMass = mass_payload + ...
        dragMassPerArea * drag_area + ...
        massHinge + ...
        numberOfSprings * massOneSpring;

    [ velocity, ~, ~ ] = jumperJumpHeight(gravity, ...
                                          airDensity, ...
                                          dragCoefficient, ...
                                          drag_area, ...
                                          efficiency, ...
                                          totalEnergy, ...
                                          totalMass);

end
